spring:
  mail:
    host: smtp.gmail.com
    username: tennistico.app@gmail.com
    password: Tennis1!
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com

  mvc:
    throw-exception-if-no-handler-found=true:
server:
  error:
    whitelabel:
      enabled=false: