spring:
  h2.console:
    path: /h2
    enabled: true

  datasource:
    hikari.jdbc-url: jdbc:h2:mem:testdb

ranking:
  pagination: 5

scheduling:
  cron:
    upcoming: 0 * * * * *
    pending: 0 * * * * *